#!/usr/bin/env php
<?php

// Bootstrap & load Laravel
define('ARTISAN', true);
require 'bootstrap.php';

$app->boot();

// Load, run & shutdown Artisan
$app->setRequestForConsoleEnvironment();

$artisan = Illuminate\Console\Application::start($app);
$status = $artisan->run();
$app->shutdown();
exit($status);
